name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Copy frontend build to backend
        run: |
          # Ensure target folder exists
          mkdir -p backend/public
          
          # Clear old files
          rm -rf backend/public/*
          
          # Copy new build
          cp -r frontend/dist/* backend/public/
